### ISSUE TITLE
Enhancement - Geocentric Horizon view / CelestialSphere of universe based off user location + date

### ISSUE THREAD

**Issue by johndpope** [ThumbWorks/AugmentedSolarSystem#46]
I've spent some days digging through this - with this image - hopefully it will make sense.
https://youtu.be/9XHoVF2G0j8?t=653

http://astro.unl.edu/classaction/animations/coordsmotion/celestialhorizon.html

<img width="589" alt="screen shot 2017-11-16 at 20 36 41" src="https://user-images.githubusercontent.com/289994/32925075-f6f996c0-cb0d-11e7-8a8d-50e5beeef0fd.png">

I think I'm looking to find a camera angle for scenekit which would create a horizon view to universe
I want to make the point of view geocentric.
the horizon which is currently the heliocentric plane - I want to tilt to the declination of earth's orbit -  with every planet above the horizon above the scenekit floor / everything below the earth beneath. the universe plane would still spin as it does. (I'm not looking to create star walk - how the view is represented is perfect. )

Not sure how hard this is -  I found this function that maybe able to be repurposed.
given a users location / instead of finding the moon - perhaps we can derive a camera angle in scenekit. the point of view - would be geocentric - as the user sees the planets above.

func findMoon(date: NSDate, longitude: Double, latitude: Double) -> (Double,Double,Double)
https://github.com/johndpope/Moon/blob/ui-heading-display/Moon/FindMoonService.swift

**Comment by johndpope** [comment]
moon app 
Optional(<+37.33233141,-122.03121860> +/- 5.00m (speed 0.00 mps / course -1.00) @ 11/17/17, 1:54:18 AM Greenwich Mean Time)
Location Authorized!
date: 6529.57940850267
Ecliptic Long: 219.861644466578
Ecliptic Lat: 4.96158472691399
SET MOON

<img width="553" alt="screen shot 2017-11-16 at 20 54 23" src="https://user-images.githubusercontent.com/289994/32925538-65ee6c7a-cb10-11e7-933a-9993fb2af63d.png">

**Comment by johndpope** [comment]
![screen shot 2017-11-17 at 2 48 15 pm](https://user-images.githubusercontent.com/289994/32965986-5d851f66-cba6-11e7-9738-18c2eafed6eb.png)
![screen shot 2017-11-17 at 2 48 10 pm](https://user-images.githubusercontent.com/289994/32965987-5d9647be-cba6-11e7-90f8-176e7be4d43f.png)
https://github.com/op1000/EarthTravel/blob/master/movie/movie_ani.mov

these objective-c classes successfully map the lat / lng co-ordinates to an object in scenekit.
https://github.com/op1000/EarthTravel/tree/master/EarthTravel/Classes

**Comment by johndpope** [comment]
fyi - @onekiloparsec

**Comment by johndpope** [comment]
I apologize for confusion as the words to describe what I want to do fail me. I need to do a drawing. 
I don't have photoshop either.
Also - I only found out today that there's such a thing called galataticLatitude and galaticLongitude.

so let me clarify this ticket -  using CoreLocationManager -  I can easily find true north as shown above from where I am. That's all easy stuff.
https://github.com/johndpope/Moon/blob/ui-heading-display/Moon/ViewController.swift


Instead of the sun being the central focus of ar, I want my point of view to be.
so above where it says **Manama** - imagine that is zoomed to street level - and I can see the universal planets spinning around the sun correctly aligned to today's date.
I say street level but as app works at the moment - being able to zoom out of state / country level would be most desirable.

The universal plane with planets would tilt accordingly to where they're actually spinning with respect to end user's location + date. This is called geocentric point of view. 

I reached out to the author of SwiftAA -  Cédric Foellmi and he mentioned

_At a fixed given point in time (assuming you keep standard epoch and equinox, of course…), you still have to take care of Earth location, and make sure you check the  (small) difference between geocentric (with Earth center as reference) and topocentric (Observer position as reference) positions._ 


I think to do this - need to break apart into smaller tickets - so I added the ability to add lat / lng position according to scenekit node in other ticket.

Perhaps - a worthy SwiftAA side piece of work would be to create some code that can create a celestial sphere in arkit this would match up to user's current location and compass baring.
<img width="859" alt="screen shot 2017-11-17 at 7 18 55 pm" src="https://user-images.githubusercontent.com/289994/32974453-35a3b31a-cbcc-11e7-8c91-f68834416a5c.png">

I just downloaded flash animate - going to review the source code.
http://physics.unl.edu/~astrodev/flashdev2/celestial_sphere/celestial_sphere101.html

**Comment by johndpope** [comment]
fyi - rotate earth to right time of day / scenekit + swift
https://github.com/gavineadie/Geometries/commit/7e35351761cc453ab7d58a3ca0b959e98cc92056

![Uploading Screen Shot 2017-11-17 at 9.07.30 PM.png…]()

**Comment by johndpope** [comment]
found this which successfully maps a lat / lng to a scenekit object
https://stackoverflow.com/questions/10473852/convert-latitude-and-longitude-to-point-in-3d-space

https://github.com/RPasecky/ARGlobe/blob/master/ARGlobe/coordinateMarker.swift
<img width="376" alt="screen shot 2017-11-17 at 9 44 56 pm" src="https://user-images.githubusercontent.com/289994/32976254-94a195da-cbe0-11e7-9671-6e3e147f460d.png">
```swift

 func convertLLAtoECEF(coordinateData: coordinateData, radius: Double) {
        //Thanks CodingAway https://stackoverflow.com/questions/10473852/convert-latitude-and-longitude-to-point-in-3d-space
        let rad = radius  //6378137.0       //Radius of the Earth (in meters)
        let f = 1.0/298.257223563  // Flattening factor WGS84 Model
        let longRad = (-coordinateData.longitude + 90) * .pi / 180
        let latRad = (coordinateData.latitude) * .pi / 180
        
        let cosLat = cos(latRad)
        let sinLat = sin(latRad)
        let FF     = pow(1.0 - f, 2)
        let C      = 1 / sqrt(pow(cosLat, 2) + FF * pow(sinLat, 2))
        let S      = C * FF
        
        self.position.x = Float((rad * C + coordinateData.altitude) * cosLat * cos(longRad))
        self.position.y = Float((rad * S + coordinateData.altitude) * sinLat)
        self.position.z = Float((rad * C + coordinateData.altitude) * cosLat * sin(longRad))
        
        print("position: \(self.position)")
        
        
    }
```

**Comment by gavineadie** [comment]
That's a quite old version of my "Geometries" testbed!
I'll bring it up to date so it actually looks like what it's meant to!

**Comment by johndpope** [comment]
![img_2091](https://user-images.githubusercontent.com/289994/32985425-72571952-cc88-11e7-947c-26ea4715c9ba.PNG)
thanks @gavineadie  for updating code base.
I found this very simple gryoscope / coremotion + scenekit code.
https://github.com/mike-ferenduros/gyrotest/blob/master/gyrotest/GyroViewController.swift

instead of the cube - I will rework it to be planet earth. the top being current location.
need to add a zenith point reflecting top of celestial sphere.

**Comment by johndpope** [comment]
some progress - https://github.com/johndpope/solarSystem-1
this hooks into coremotion - and rotates scenekit nodes according to orientation of phone.
it's currently rigged up to the sun. It's using a different code base to AugmentedSolarSystem - but currently code is simpler while I work out logic. for the geocentric view to work / I need to be able to determine the sidereal / altitude / azimuth - https://github.com/onekiloparsec/SwiftAA/issues/74

Not sure what' necessary from scenekit - but I need the elliptical planes to be gymbal locked to earth. Currently in my code - when I rotate the sun - the planets continue merrily along their previous paths.  when I adjust the earth, I need all the planets to adjust their planes accordingly.

**Comment by onekiloparsec** [comment]
Similarly to coordinates conversion, obtaining the sidereal time is just a matter of converting the date (or JulianDay) so sidereal time, using the geographic coordinates. See the method `meanLocalSiderealTime` in the `JulianDay` struct/extension.

**Comment by johndpope** [comment]
maths for calculating geocentric position of planets. 
http://www.stjarnhimlen.se/comp/tutorial.html#14

**Comment by onekiloparsec** [comment]
Still, SwiftAA provides everything you need to make these calculations. Probably with more accuracy than this web page.

**Comment by johndpope** [comment]
I believe SwiftAA needs an orrery for reference purposes
/ maybe using scenekit / arkit or metal
maybe augmented reality - maybe without. 

this seems to be the flagship 
http://mgvez.github.io/jsorrery/

https://github.com/mgvez/jsorrery/tree/master/src/algorithm

**Comment by johndpope** [comment]
I want to build something like this app Cosmic Watch - it's superb.
![img_2137](https://user-images.githubusercontent.com/289994/33243252-6e3ccd34-d2b0-11e7-9527-b5150f084b01.jpg)

**Comment by johndpope** [comment]
so digging through docs on swiftAA - the class Planet supposedly includes equatorialCoordinates.
if somehow the planets in scenekit shared the logic of the respective Planet node then perhaps we can tap into this variable to determine the position. Would need to translate betwen the two.

```swift
/// The coordinates of the object in the equatorial system (based on Earth equator), with the Earth's center as its origin.
    public var equatorialCoordinates: EquatorialCoordinates {
        get { return self.apparentGeocentricEquatorialCoordinates }
    }

    /// The heliocentric coordinates of the planet in the ecliptic system (based on planet orbits plane). That is, its apparent position on the celestial sphere, as
    /// as it would be seen by an observer at rest at the barycenter of the solar system, and referred to the 
    /// instantaneous equator, ecliptic and equinox.
    /// It accounts for 1) the effect of light-time and 2) the effect of the Earth motion. See AA p224.
    public var heliocentricEclipticCoordinates: EclipticCoordinates {
        get {
            let longitude = KPCAAEclipticalElement_EclipticLongitude(self.julianDay.value, self.planet, self.highPrecision)
            let latitude = KPCAAEclipticalElement_EclipticLatitude(self.julianDay.value, self.planet, self.highPrecision)
            // Using standard epoch, thus standard value for the equinox, thus the mean obliquity.
            return EclipticCoordinates(lambda: Degree(longitude), beta: Degree(latitude))
        }
    }
```

**Comment by johndpope** [comment]
this method - translates 
https://github.com/polymorphic92/Up-Down-Sun/blob/7f5865dc2b29f83f9a8d1ff348b8e74c1f101ea4/Up%20Down%20Sun/MoonUtils.swift

From @polymorphic92 - these methods appear to map heliocentric to geocentric positions.


```swift

import Foundation

class MoonUtils {
	
	class func getMoonCoords(d:Double) -> GeocentricCoordinates {
		// geocentric ecliptic coordinates of the moon
		
		let L:Double = Constants.RAD() * (218.316 + 13.176396 * d);   // ecliptic longitude
		let M:Double = Constants.RAD() * (134.963 + 13.064993 * d);   // mean anomaly
		let F:Double = Constants.RAD() * (93.272 + 13.229350 * d);    // mean distance
		
		let l:Double  = L + Constants.RAD() * 6.289 * sin(M);    // longitude
		let b:Double  = Constants.RAD() * 5.128 * sin(F);        // latitude
		let dt:Double = 385001 - 20905 * cos(M);     // distance to the moon in km
		
		return GeocentricCoordinates(rightAscension: PositionUtils.getRightAscensionL(l, b: b), declination: PositionUtils.getDeclinationL(l, b: b), distance: dt)
	}
}


public class SunCalc {
	let J0:Double = 0.0009
	
	var sunrise:NSDate
	var sunriseEnd:NSDate
	var goldenHourEnd:NSDate
	var solarNoon:NSDate
	var goldenHour:NSDate
	var sunsetStart:NSDate
	var sunset:NSDate
	var dusk:NSDate
	var nauticalDusk:NSDate
	var night:NSDate
	var nadir:NSDate
	var nightEnd:NSDate
	var nauticalDawn:NSDate
	var dawn:NSDate
	
	class func getSetJ(h:Double, phi:Double, dec:Double, lw:Double, n:Double, M:Double, L:Double) -> Double {
		let w:Double = TimeUtils.getHourAngleH(h, phi: phi, d: dec)
		let a:Double = TimeUtils.getApproxTransitHt(w, lw: lw, n: n)
		
		return TimeUtils.getSolarTransitJDs(a, M: M, L: L)
	}
	
	class func getTimes(date:NSDate, latitude:Double, longitude:Double) -> SunCalc {
		return SunCalc(date:date, latitude:latitude, longitude:longitude)
	}
	
	class func getSunPosition(timeAndDate:NSDate, latitude:Double, longitude:Double) -> SunPosition {
		let lw:Double = Constants.RAD() * -longitude
		let phi:Double = Constants.RAD() * latitude
		let d:Double = DateUtils.toDays(timeAndDate)
		
		let c:EquatorialCoordinates = SunUtils.getSunCoords(d)
		let H:Double = PositionUtils.getSiderealTimeD(d, lw: lw) - c.rightAscension
		
		return SunPosition(azimuth: PositionUtils.getAzimuthH(H, phi: phi, dec: c.declination), altitude: PositionUtils.getAltitudeH(H, phi: phi, dec: c.declination))
	}
	
	class func getMoonPosition(timeAndDate:NSDate, latitude:Double, longitude:Double) -> MoonPosition {
		let lw:Double = Constants.RAD() * -longitude
		let phi:Double = Constants.RAD() * latitude
		let d:Double = DateUtils.toDays(timeAndDate)
		
		let c:GeocentricCoordinates = MoonUtils.getMoonCoords(d)
		let H:Double = PositionUtils.getSiderealTimeD(d, lw: lw) - c.rightAscension
		var h:Double = PositionUtils.getAltitudeH(H, phi: phi, dec: c.declination)
		
		// altitude correction for refraction
		h = h + Constants.RAD() * 0.017 / tan(h + Constants.RAD() * 10.26 / (h + Constants.RAD() * 5.10));
		
		return MoonPosition(azimuth: PositionUtils.getAzimuthH(H, phi: phi, dec: c.declination), altitude: h, distance: c.distance)
	}
	
	class func getMoonIllumination(timeAndDate:NSDate) -> MoonIllumination {
		let d:Double = DateUtils.toDays(timeAndDate)
		let s:EquatorialCoordinates = SunUtils.getSunCoords(d)
		let m:GeocentricCoordinates = MoonUtils.getMoonCoords(d)
		
		let sdist:Double = 149598000; // distance from Earth to Sun in km
		
		let phi:Double = acos(sin(s.declination) * sin(m.declination) + cos(s.declination) * cos(m.declination) * cos(s.rightAscension - m.rightAscension))
		let inc:Double = atan2(sdist * sin(phi), m.distance - sdist * cos(phi))
		let angle:Double = atan2(cos(s.declination) * sin(s.rightAscension - m.rightAscension), sin(s.declination) * cos(m.declination) - cos(s.declination) * sin(m.declination) * cos(s.rightAscension - m.rightAscension))
		
		let fraction:Double = (1 + cos(inc)) / 2
		let phase:Double = 0.5 + 0.5 * inc * (angle < 0 ? -1 : 1) / Constants.PI()
		
		return MoonIllumination(fraction: fraction, phase: phase, angle: angle)
	}
	
	init(date:NSDate, latitude:Double, longitude:Double) {
		let lw:Double = Constants.RAD() * -longitude
		let phi:Double = Constants.RAD() * latitude
		let d:Double = DateUtils.toDays(date)
		
		let n:Double = TimeUtils.getJulianCycleD(d, lw: lw)
		let ds:Double = TimeUtils.getApproxTransitHt(0, lw: lw, n: n)
		
		let M:Double = SunUtils.getSolarMeanAnomaly(ds)
		let L:Double = SunUtils.getEclipticLongitudeM(M)
		let dec:Double = PositionUtils.getDeclinationL(L, b: 0)
		
		let Jnoon:Double = TimeUtils.getSolarTransitJDs(ds, M: M, L: L)
		
		self.solarNoon = DateUtils.fromJulian(Jnoon)
		self.nadir = DateUtils.fromJulian(Jnoon - 0.5)
		
		// sun times configuration (angle, morning name, evening name)
		// unrolled the loop working on this data:
		// var times = [
		//             [-0.83, 'sunrise',       'sunset'      ],
		//             [ -0.3, 'sunriseEnd',    'sunsetStart' ],
		//             [   -6, 'dawn',          'dusk'        ],
		//             [  -12, 'nauticalDawn',  'nauticalDusk'],
		//             [  -18, 'nightEnd',      'night'       ],
		//             [    6, 'goldenHourEnd', 'goldenHour'  ]
		//             ];
		
		var h:Double = -0.83
		var Jset:Double = SunCalc.getSetJ(h * Constants.RAD(), phi: phi, dec: dec, lw: lw, n: n, M: M, L: L)
		var Jrise:Double = Jnoon - (Jset - Jnoon)
		
		self.sunrise = DateUtils.fromJulian(Jrise)
		self.sunset = DateUtils.fromJulian(Jset)
		
		h = -0.3;
		Jset = SunCalc.getSetJ(h * Constants.RAD(), phi: phi, dec: dec, lw: lw, n: n, M: M, L: L)
		Jrise = Jnoon - (Jset - Jnoon)
		self.sunriseEnd = DateUtils.fromJulian(Jrise)
		self.sunsetStart = DateUtils.fromJulian(Jset)
		
		h = -6;
		Jset = SunCalc.getSetJ(h * Constants.RAD(), phi: phi, dec: dec, lw: lw, n: n, M: M, L: L)
		Jrise = Jnoon - (Jset - Jnoon)
		self.dawn = DateUtils.fromJulian(Jrise)
		self.dusk = DateUtils.fromJulian(Jset)
		
		h = -12;
		Jset = SunCalc.getSetJ(h * Constants.RAD(), phi: phi, dec: dec, lw: lw, n: n, M: M, L: L)
		Jrise = Jnoon - (Jset - Jnoon)
		self.nauticalDawn = DateUtils.fromJulian(Jrise)
		self.nauticalDusk = DateUtils.fromJulian(Jset)
		
		h = -18;
		Jset = SunCalc.getSetJ(h * Constants.RAD(), phi: phi, dec: dec, lw: lw, n: n, M: M, L: L)
		Jrise = Jnoon - (Jset - Jnoon)
		self.nightEnd = DateUtils.fromJulian(Jrise)
		self.night = DateUtils.fromJulian(Jset)
		
		h = 6;
		Jset = SunCalc.getSetJ(h * Constants.RAD(), phi: phi, dec: dec, lw: lw, n: n, M: M, L: L)
		Jrise = Jnoon - (Jset - Jnoon)
		self.goldenHourEnd = DateUtils.fromJulian(Jrise)
		self.goldenHour = DateUtils.fromJulian(Jset)

	}
}
```

**Comment by johndpope** [comment]
Forgive this code sprawl above - getting head around the terminology.
Digging through your code 

![screen shot 2017-12-02 at 8 38 01 pm](https://user-images.githubusercontent.com/289994/33521482-b6580e4a-d7a0-11e7-8aa0-7a05fcc29c6c.png)


this calls  updatePlanetLocation which seems to rotate planet.


```swift
    func updatePlanetLocation(_ coords: EclipticCoordinates) {
        let latitude = Float(coords.celestialLatitude.magnitude)
        let longitude = Float(coords.celestialLongitude.magnitude)
        let latitudeInRadians = latitude * Float.pi / 180 // not used??
        let longitudeInRadians = longitude * Float.pi / 180
        self.rotation = SCNVector4Make(0, 1, 0, longitudeInRadians)
    }
```

What I need to achieve the heliocentric POV - I think is 'just' to map the heliocentricEclipticCoordinates:EclipticCoordinates to a scenekit x,yz, position.



```swift


 /// The heliocentric coordinates of the planet in the ecliptic system (based on planet orbits plane). That is, its apparent position on the celestial sphere, as
    /// as it would be seen by an observer at rest at the barycenter of the solar system, and referred to the 
    /// instantaneous equator, ecliptic and equinox.
    /// It accounts for 1) the effect of light-time and 2) the effect of the Earth motion. See AA p224.
    public var heliocentricEclipticCoordinates: EclipticCoordinates {
        get {
            let longitude = KPCAAEclipticalElement_EclipticLongitude(self.julianDay.value, self.planet, self.highPrecision)
            let latitude = KPCAAEclipticalElement_EclipticLatitude(self.julianDay.value, self.planet, self.highPrecision)
            // Using standard epoch, thus standard value for the equinox, thus the mean obliquity.
            return EclipticCoordinates(lambda: Degree(longitude), beta: Degree(latitude))
        }
    }

```

**Comment by johndpope** [comment]
I think for me to get this working - need to take a step back and build an armillary sphere - then drop it into ARKit.

![520x293bb 3](https://user-images.githubusercontent.com/289994/33521675-c821914a-d7a6-11e7-91bb-be23215c6c1b.jpg)

![520x293bb](https://user-images.githubusercontent.com/289994/33521674-c25e8826-d7a6-11e7-86d9-0cb6a1481d27.jpg)


![img_a562217f2e80-1](https://user-images.githubusercontent.com/289994/33521687-e9f85650-d7a6-11e7-914b-119524697af8.jpeg)

**Comment by johndpope** [comment]
https://vimeo.com/55019500

![screen shot 2017-12-02 at 9 29 29 pm](https://user-images.githubusercontent.com/289994/33521719-e80706ce-d7a7-11e7-949e-8a9bcbe84bf0.png)
