### ISSUE TITLE
enhancement - performance - image assets

### ISSUE THREAD

**Issue by johndpope** [ThumbWorks/AugmentedSolarSystem#50]
![img_2086](https://user-images.githubusercontent.com/289994/32982012-88e541f4-cc4b-11e7-8ff9-d408df2bf6b0.PNG)

for some reason to be determined - this codebase runs much much faster.
https://github.com/skull8888888/solarSystem

credits - @skull8888888 

probably could have a lot to do with much smaller image assets
<img width="782" alt="screen shot 2017-11-18 at 10 32 39 am" src="https://user-images.githubusercontent.com/289994/32982025-d5c99466-cc4b-11e7-8386-54a72f60dbc8.png">

**Comment by rodericj** [comment]
I've gone ahead and made a few of these changes in this recent commit. I don't really have a good sense of the breaking point for these assets on my devices. I'm curious to see how these play out on all devices tbh. 

Sounds like a cool blog post actually.

**Comment by johndpope** [comment]
nice. will test it out. 
![screen shot 2017-11-30 at 1 09 27 pm](https://user-images.githubusercontent.com/289994/33446963-bcb586dc-d5cf-11e7-9012-ef9035dd0c5c.png)

**Comment by rodericj** [comment]
I'd love to hear how it works for you. TBH I haven't tested this yet I was in a moving vehicle :(

**Comment by johndpope** [comment]
feels lighter.
