### ISSUE TITLE
enhancement - sun to provide ambient lighting for spheres

### ISSUE THREAD

**Issue by johndpope** [ThumbWorks/AugmentedSolarSystem#52]
https://github.com/dmojdehi/SwiftGlobe
reference code
![tv_screen](https://user-images.githubusercontent.com/289994/32996903-13accc10-cd57-11e7-9af9-def20531d674.png)

**Comment by rodericj** [comment]
Is this not happening for you?

**Comment by johndpope** [comment]
my bad- been using this other codebase while I nut out the geocentric point of view  https://github.com/johndpope/solarSystem-1
