### ISSUE TITLE
bug - latest swift aa - fails

### ISSUE THREAD

**Issue by johndpope** [ThumbWorks/AugmentedSolarSystem#53]
**carthage build platform=ios**
 xcode 9.1

Checking out SwiftAA at "2.0"

<img width="1221" alt="screen shot 2017-11-19 at 21 04 29" src="https://user-images.githubusercontent.com/289994/32998991-5d5147c2-cd6d-11e7-9a8a-23684d8e695f.png">
<img width="861" alt="screen shot 2017-11-19 at 21 06 57" src="https://user-images.githubusercontent.com/289994/32999022-9bb0c8f8-cd6d-11e7-9301-e31311d6da2b.png">

**Comment by rodericj** [comment]
It’s built off of this https://github.com/ThumbWorks/SwiftAA

**Comment by johndpope** [comment]
ok thanks
perhaps need to update carthage file accordingly
github "ThumbWorks/SwiftAA"

**Comment by johndpope** [comment]
fyi

this is resolved - but needed following actions.

using github "ThumbWorks/SwiftAA" > 

<img width="539" alt="screen shot 2017-11-30 at 2 14 42 pm" src="https://user-images.githubusercontent.com/289994/33450130-d3f781ca-d5d8-11e7-938a-98379b665181.png">
drag in framework into project.

https://github.com/mixpanel/mixpanel-iphone/issues/345

but then update build phases to include framework  
<img width="1238" alt="screen shot 2017-11-30 at 2 14 06 pm" src="https://user-images.githubusercontent.com/289994/33450107-c3207aaa-d5d8-11e7-9aa3-6d15613774a3.png">
